table 'City Lookup Table'
	lineageTag: 09b8ef99-0619-4052-b500-bc1ff16d31b7

	column City
		dataType: string
		lineageTag: 508dd355-fac6-4098-badc-7f2e67b4f7df
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 93f4e161-ee2a-4bde-92cb-8602bfc0ac7a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 7a2b0058-99cf-434a-9f3c-81df5d7c12c5
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 42da0b47-358a-44ed-b48e-dc8ed1d156bb
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy 'Country Hierarchy'
		lineageTag: 8d3e9ab1-0d2a-4c65-8352-5815c4e778ba

		level Country
			lineageTag: c7938232-8afc-4b73-b732-6cb4a092a7e1
			column: Country

		level City
			lineageTag: 1bef1e44-5d02-4aec-acee-cf3fd5c3e6b1
			column: City

	partition 'City Lookup Table' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\juhan\Downloads\city_attributes.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"City", type text}, {"Country", type text}, {"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

