table 'Pressure Data'
	lineageTag: e733f3df-f9f7-4e53-a2a6-5ca00d290d8d

	column Datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: f2f5c7a6-19b4-4fe0-994c-b12d89f0ebcc
		summarizeBy: none
		sourceColumn: Datetime

		variation Variation
			isDefault
			relationship: 7acb357d-4697-4d4f-8b83-7d89a49f8280
			defaultHierarchy: LocalDateTable_09fd2460-5298-40e3-bfa8-bc7e24fd03d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 15af24fe-2f4b-4742-81c2-a7cc0bfb9db4
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Pressure
		dataType: int64
		formatString: 0
		lineageTag: d1f1a84e-c41c-4e71-9e3a-0e6b9045cc10
		summarizeBy: sum
		sourceColumn: Pressure

		annotation SummarizationSetBy = Automatic

	partition 'Pressure Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\juhan\Downloads\pressure.csv"),[Delimiter=",", Columns=37, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"datetime", type datetime}, {"Vancouver", Int64.Type}, {"Portland", Int64.Type}, {"San Francisco", Int64.Type}, {"Seattle", Int64.Type}, {"Los Angeles", Int64.Type}, {"San Diego", Int64.Type}, {"Las Vegas", Int64.Type}, {"Phoenix", Int64.Type}, {"Albuquerque", Int64.Type}, {"Denver", Int64.Type}, {"San Antonio", Int64.Type}, {"Dallas", Int64.Type}, {"Houston", Int64.Type}, {"Kansas City", Int64.Type}, {"Minneapolis", Int64.Type}, {"Saint Louis", Int64.Type}, {"Chicago", Int64.Type}, {"Nashville", Int64.Type}, {"Indianapolis", Int64.Type}, {"Atlanta", Int64.Type}, {"Detroit", Int64.Type}, {"Jacksonville", Int64.Type}, {"Charlotte", Int64.Type}, {"Miami", Int64.Type}, {"Pittsburgh", Int64.Type}, {"Toronto", Int64.Type}, {"Philadelphia", Int64.Type}, {"New York", Int64.Type}, {"Montreal", Int64.Type}, {"Boston", Int64.Type}, {"Beersheba", Int64.Type}, {"Tel Aviv District", Int64.Type}, {"Eilat", Int64.Type}, {"Haifa", Int64.Type}, {"Nahariyya", Int64.Type}, {"Jerusalem", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"datetime", "Datetime"}}),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Renamed Columns", {"Vancouver", "Portland", "San Francisco", "Seattle", "Los Angeles", "San Diego", "Las Vegas", "Phoenix", "Albuquerque", "Denver", "San Antonio", "Dallas", "Houston", "Kansas City", "Minneapolis", "Saint Louis", "Chicago", "Nashville", "Indianapolis", "Atlanta", "Detroit", "Jacksonville", "Charlotte", "Miami", "Pittsburgh", "Toronto", "Philadelphia", "New York", "Montreal", "Boston", "Beersheba", "Tel Aviv District", "Eilat", "Haifa", "Nahariyya", "Jerusalem"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Only Selected Columns",{{"Value", "Pressure"}, {"Attribute", "City"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

